development:
  pocket:
    client_id: ''
    client_secret: ''
  db:
    host: 'localhost'
    port: 3306
    database: ''
    username: ''
    password: ''
  log_file: ''

production:
  pocket:
    client_id: ''
    client_secret: ''
  db:
    host: 'localhost'
    port: 3306
    database: ''
    username: ''
    password: ''
  log_file: ''
